spring:
   profiles:
      active:
      - dev
---
spring:
  profiles: dev
  application:
      name: trycloud-test-dev
---
spring:
 profiles: default
 application:
      name: trycloud-test-default