spring:
  profiles:
    active:
      - dev
---
server:
 port: 7001
spring:
  profiles: dev
  security:
    user:
      name: fxy
      password: 1234
  application:
    name: trycloud-config-eureka-client
---

server:
 port: 7002
 
spring:
  profiles: beta
  security:
    user:
      name: fxy
      password: 1234
  application:
    name: trycloud-config-eureka-client