spring:
  profiles:
    active:
      - dev
---
server:
 port: 7001
eureka:
 server:
  eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  enable-self-preservation: false #设置为false表示关闭保护模式
 client: 
  fetch-registry: false
  register-with-eureka: false
  service-url:  
   defaultZone: http://fxy:1234@eureka1:7001/eureka
 instance: #eureak实例定义
  hostname:eureka1#定义 Eureka 实例所在的主机名称
spring: 
 profiles: dev
 security: 
  user:
   name: fxy
   password: 1234
 application: 
  name: trycloud-config-eureka-client
---
server:
 port: 7002
eureka:
 server:
  eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  enable-self-preservation: false #设置为false表示关闭保护模式
 client: 
  fetch-registry: false
  register-with-eureka: false
  service-url: 
   defaultZone: http://fxy:1234@eureka1:7002/eureka
 instance: #eureak实例定义
  hostname:eureka2#定义 Eureka 实例所在的主机名称
spring: 
 profiles: beta
 security: 
  user:
   name: fxy
   password: 1234
 application: 
  name: trycloud-config-eureka-client
